## 1D NUMPY

In [31]:
import numpy as np
arr=np.array([10,11,12,13,14,15])
print("1st five Array:", arr[:5])
print("Last five Array:", arr[-5:])

1st five Array: [10 11 12 13 14]
Last five Array: [11 12 13 14 15]


## MATRIX

In [29]:
matrix=np.arange(1,13).reshape(3,4)
print("Matrix:")
print(matrix)
print("Second Row:", matrix[1])
print("Last Column:", matrix[:,-1])

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second Row: [5 6 7 8]
Last Column: [ 4  8 12]


## DOT PRODUCT

In [33]:
A=np.array([1,2,3,4])
B=np.array([10,20,30,40])
print("Element wise addition:", A+B)
dot=0
for i in range(len(A)):
    dot=dot+A[i]*B[i]
print("Dot Product:", dot)

Element wise addition: [11 22 33 44]
Dot Product: 300
